config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'

  resources :products

  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
has_many :line_items, dependent: :destroy

def add_product(product)
  current_item = line_items.find_by(product_id: product.id)
  if current_item
    current_item.quantity += 1
  else
    current_item = line_items.build(product_id: product.id)
  end
  current_item
end

def total_price
  line_items.to_a.sum { |item| item.total_price }
end

end 

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart



  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  validates :title, :description, :price, presence: true
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :price, numericality: { greater_than_or_equal_to: 0.01}

  has_many :line_items
  monetize :price_cents

  before_destroy :ensure_not_referenced_by_any_line_item

  private

  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'line items present')
      throw :abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true 
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count 
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:create, :update, :destroy]

rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: 'Cart has been emptied motherfucker!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "attempt to access invalid cart #{params[:id]}"
      redirect_to store_index_url, notice: 'invalid cart you mother fucking hack!'
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_action :authorize

  include CurrentCart
  before_action :set_cart

# the order of methods matter. e.g. if I put the coutner method first here it breaks the page. Why is that?

   def index
    @count = counter
    @counter_message = "you know you want to - you've been to this page #{@count} times, buy it already"
    @products = Product.order(:title)
    # what is going on here? I'm exposing the proudct variable
    @product = Product
  end

private

def counter
  if session[:counter].nil?
     session[:counter] = 0
   end
     session[:counter] += 1
   end
 end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.order(:name)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User #{@user.name} was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
      format.html { redirect_to users_url, notice: 'User #{@user.name} was successfully created.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_if(condition, record)
    if condition
      render record
    end
  end 
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome Your Highness</h1>

<p>It's <%= Time.now %>
  We have <%= pluralize(@total_orders, "order") %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>A little store to buy things!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://js.stripe.com/v3/"></script>

    <!-- Just an image -->
<nav class="navbar navbar-light bg-light">
  <a class="navbar-brand" href="/">
    <%= image_tag("logo.svg") %>
  </a>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Store</a>

<% if session[:user_id] %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link", <%= link_to 'Orders', orders_path %><span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link", <%= link_to 'Products', products_path %><span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link", <%= link_to 'Users', users_path %><span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link", <%= link_to 'Logout', logout_url, method: :delete %></a>
        </li>
      </ul>
    </div>
    <% else %>

    <a class="navbar-brand" <%= link_to 'Login', login_path %></a>

    <% end %>
  </nav>
</nav>
  </head>

  <body>
    <header>
      <h1><%= @page_title %></h1>
    </header>
    <div class="container-fluid">
      <div class="row">
    <div class="col-sm-3">
        <div class="card">
         <%= render_if @cart && @cart.line_items.any?, @cart %>
         </div>
         <div class="card">
         <div class="card-body">
           <h5 class="card-title">Why Haven't You Bought Something Yet?</h5>
           <p class="card-text"><%= @counter_message %></p>
         </div>
    </div>
  </div>
  <div class="col">
    <main class='<%= controller.controller_name %>'>
    <%= yield %>
    </main>
    </div>
  </div>
</div>
  </body>
</html>